spring:
  application:
    name: hello-serice
dubbo:
  provider:
    application: ${spring.application.name}
    filter: sign
  scan:
    base-packages: com.ddnet.dubbo.service
  protocol:
    name: dubbo
    port: 12345
  registry:
    address: N/A
