spring:
  application:
    name: hello-serice
dubbo:
  provider:
    application: ${spring.application.name}
    filter: sign
    parameters:
      signtoken: ${spring.application.name}-signtoken
  scan:
    base-packages: com.ddnet.dubbo.service
  protocol:
    name: dubbo
    port: 12345
  registry:
    address: zookeeper://172.16.10.141:2181
  application:
    qos-enable: false