spring:
  application:
    name: hello-serice
dubbo:
  provider:
    application: ${spring.application.name}
    filter: sign
    parameters:
      signtoken: ${spring.application.name}-signtoken
    tag: server1
  scan:
    base-packages: com.ddnet.dubbo.service
  protocol:
    name: dubbo
    port: 12345
  registry:
    address: 127.0.0.1:2181
#    username: zookeeper
#    password: zookeeper
#    client: curator
    protocol: zookeeper
  application:
    qos-enable: false